### PR TITLE
[feat] logger: provide a default winston logger

### PR DESCRIPTION
**Pull request by meriamBenSassi**
# [feat] logger: provide a default winston logger

## Description

Provide a default winston logger and the ability to customise the options
 
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by amarlankri — COMMENTED** [review]
I wonder if we should update `Logger.interface.ts`, since it doesn't contain explicitly a `log` method. What do you think?

**Comment by meriamBenSassi** [comment]
> I wonder if we should update `Logger.interface.ts`, since it doesn't contain explicitly a `log` method. What do you think?

@amarlankri I don't know If I understood your suggestion, since I replaced `info` by `log` in the `Logger.interface.ts`

**Comment by amarlankri** [comment]
> > I wonder if we should update `Logger.interface.ts`, since it doesn't contain explicitly a `log` method. What do you think?
> 
> @amarlankri I don't know If I understood your suggestion, since I replaced `info` by `log` in the `Logger.interface.ts`

My bad, I didn't see it!

**Review by amarlankri — APPROVED** [review]

**Review by ccoeurderoy — COMMENTED** [review]
I'm afraid it won't work with winston. Have a look at the [log type definition](https://github.com/winstonjs/winston/blob/master/index.d.ts#L61)

**Comment by meriamBenSassi** [comment]
> I'm afraid it won't work with winston. Have a look at the [log type definition](https://github.com/winstonjs/winston/blob/master/index.d.ts#L61)

There is a log method No ?  https://github.com/winstonjs/winston/blob/master/index.d.ts#L100

**Comment by ccoeurderoy** [comment]
> > I'm afraid it won't work with winston. Have a look at the [log type definition](https://github.com/winstonjs/winston/blob/master/index.d.ts#L61)
> 
> There is a log method No ? https://github.com/winstonjs/winston/blob/master/index.d.ts#L100

Yes but have a look at its definition:

```ts
   interface LogMethod {
    (level: string, message: string, callback: LogCallback): Logger;
    (level: string, message: string, meta: any, callback: LogCallback): Logger;
    (level: string, message: string, ...meta: any[]): Logger;
    (entry: LogEntry): Logger;
    (level: string, message: any): Logger;
  }
```

The first argument is made to specify the level, not the message

**Comment by meriamBenSassi** [comment]
@ccoeurderoy  obviously we cannot be compatible to all existant loggers, so maybe when integrating it, the developer should encapsulate its logger into a class that much our interface

**Comment by ccoeurderoy** [comment]
> @ccoeurderoy obviously we cannot be compatible to all existant loggers, so maybe when integrating it, the developer should encapsulate its logger into a class that much our interface

I agree, or we can just use a basic winston, and gives the ability for a developer to change default logger options

**Review by ccoeurderoy — APPROVED** [review]

**Review by ccoeurderoy — APPROVED** [review]

**Pull request merged**
